# deny-all
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: dev
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# iam
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: iam
  namespace: dev
spec:
  podSelector:
    matchLabels:
      name: iam-deployment-pod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
---
# iam-call
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: iam-call
  namespace: dev
spec:
  podSelector:
    matchLabels:
      name: iam-call-deployment-pod
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
        - ipBlock:
            cidr: 10.42.0.0/16
      ports:
        - protocol: TCP
          port: 6443
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53