# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: deny-all
#   namespace: dev
# spec:
#   podSelector: {}
#   policyTypes:
#     - Ingress
#     - Egress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-iam-call-k8s-api
#   namespace: dev
# spec:
#   podSelector: {}
#   policyTypes:
#     - Egress
#   egress:
#     - to:
#         - ipBlock:
#             cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 443
#         - protocol: TCP
#           port: 6443
#     - to:
#         - namespaceSelector:
#             matchLabels:
#               kubernetes.io/metadata.name: kube-system
#           podSelector:
#             matchLabels:
#               component: kube-apiserver
#       ports:
#         - protocol: TCP
#           port: 443
#         - protocol: TCP
#           port: 6443